### ISSUE TITLE
Preserve alignment

### ISSUE THREAD

**Issue by developocalypse** [silkfire/Pastel#18]
Is there any way to preserve alignment when using Pastel, so that the first example output matches the second example output, but with color?
```
Enumerable.Range(1, 20).ToList().ForEach(i =>
{
    WriteLine($"item: {i,2} data: {Math.Round(1M / i, 4).ToString().Pastel(LightBlue),-6} another field: {Math.Pow(i, 3),5}");
});

Enumerable.Range(1, 20).ToList().ForEach(i =>
{
    WriteLine($"item: {i,2} data: {Math.Round(1M / i, 4),-6} another field: {Math.Pow(i, 3),5}");
});

```

**Comment by silkfire** [comment]
The reason why the text becomes aligned in an unexpected way is because of the very characters that Pastel wraps the string with. The ANSI codes are invisible but are still part of the final string.

In your example, the visible length of the colored string is 6 characters, but the actual length of the string is 29.
You could solve this by storing the total length of an empty colorized string plus your desired aligned length.

Because this length is variable, you can't specify it as a formatting argument, only constants are allowed. A solution to this is to use `PadRight` (or `PadLeft`).

```csharp
var calculatedAlignmentLength = 6 + "".Pastel(Color.LightBlue).Length;

Enumerable.Range(1, 20).ToList().ForEach(i =>
{
   Console.WriteLine($"item: {i,2} data: {Math.Round(1M / i, 4).ToString(CultureInfo.InvariantCulture).Pastel(Color.LightBlue).PadRight(calculatedAlignmentLength)} another field: {Math.Pow(i, 3),5}");
});
```

![image](https://user-images.githubusercontent.com/1554615/89742867-f1d1ca80-da9d-11ea-8e42-5c4a37ab654c.png)

**Comment by developocalypse** [comment]
Brilliant, thanks.
I stuck it in an extension method. Negative values to pad left.
```
public static class PastelObjectExtensions
{
    public static string Padstel(this object input, Color color, int alignment)
    {
        if (alignment >= 0)
        {
            var calculatedAlignmentLength = alignment + "".Pastel(color).Length;
            return input.ToString().Pastel(color).PadRight(calculatedAlignmentLength);
        }
        else
        {
            var calculatedAlignmentLength = -alignment + "".Pastel(color).Length;
            return input.ToString().Pastel(color).PadLeft(calculatedAlignmentLength);
        }
    }
}
```

**Comment by silkfire** [comment]
Glad it worked out for you. PS. Love the name of that method 😄
