### ISSUE TITLE
Don't work alignment

### ISSUE THREAD

**Issue by kotmitrik** [silkfire/Pastel#25]
// this without alignment
string coloredFormat = String.Format("{0,-18}{1,-2}{2}", "SomeName".Pastel(Color.Aqua), "=", "0.03");
Console.WriteLine(coloredFormat);
// or this
Console.WriteLine("{0,-18}{1,-2}{2}", "SomeName".Pastel(Color.Aqua), "=", "0.03");

// this with alignment
string normalFormat = String.Format("{0,-18}{1,-2}{2}", "SomeName", "=", "0.03");
Console.WriteLine(normalFormat);
// or this
Console.WriteLine("{0,-18}{1,-2}{2}", "SomeName", "=", "0.03");

**Comment by silkfire** [comment]
This happens because the alignment takes into account the real number of characters - including the invisible ANSI codes added by Pastel. You'd have to calculate the difference and subtract that from the alignment value:

```csharp
const string @string = "SomeName";                         // Original to string to colorize
var stringPastel = @string.Pastel(Color.Aqua);            // Colorized string

string coloredFormat = string.Format($"{{0,{-18 - (stringPastel.Length - @string.Length)}}}{{1,-2}}{{2}}", stringPastel, "=", "0.03");

Console.WriteLine(coloredFormat);
```
Result:

![image](https://user-images.githubusercontent.com/1554615/167136107-7ca41edc-bc7c-47c6-bb91-05bda09582f4.png)

**Comment by kotmitrik** [comment]
Thanks!

**Comment by kotmitrik** [comment]
Thanks!
